logging:
  level:
    root: WARN
    org:
      springframework: TRACE
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/billing
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
