logging:
  level:
    root: WARN
    org:
      springframework: TRACE
server:
  servlet:
    contextPath: /api
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/billing
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true

application:
  cron:
    expression: 0 */1 * * * ?
  notification:
    choose: true
  sms:
    sender:
     server:
        url: http://localhost:8081/api
        send-sms-endpoint: /send-sms